Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,12 +1,7 @@
 #!/usr/bin/env bash 
 
 
-#                                  @Alamy3
-#   @Alamy3
-#     
-#                @Alamy3
-#                                @Alamy3
-#                                                            @Alamy3
+
 #---------------------------------------------------------------------
 cd $(cd $(dirname $0); pwd)
  
@@ -22,16 +17,17 @@ Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
 echo -e "${GREEN}
+▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
+▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
+▇▇          ▇ @Alamy3   ▇         ▇▇           ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
+▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @DT_TC
+▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @DT_TC  ▇▄                 ▇▇                 ▇▇
+▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source ALAMY BY @DT_TC
 
-                    
-       ▇ @Alamy3   ▇                     ▄▇▄▄▄▄▄▇▄                            
-    ▄▇                                           ¦ Dev : @Alamy3
- ▄▇ ¦ Dev : @Alamy3                   
-                                                               ¦ Source Alamy BY @DT_TC
 ----------------------------------------------------------------------${CNIL}"
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source Alamy 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source ALAMY 
 ${CNIL}";
 exit;
 fi
@@ -41,7 +37,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source Alamy${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source ALAM${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -70,10 +66,9 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "Alamy"; then
-screen -S Alamy ./run R
+if ! screen -list | grep -q "ZORO"; then
+screen -S ZORO ./run R
 fi
-screen -S Alamy -X kill
-screen -S Alamy ./run R
+screen -S ZORO -X kill
+screen -S ZORO ./run R
 fi
-
